steps:
  - name: node:16.17.1
    entrypoint: npm
    args: ["install"]
  - name: node:16.17.1
    entrypoint: npm
    args: ["run", "build"]
  - name: node:16.17.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}"
      - "NEXT_PUBLIC_SENDGRID_API_KEY=${_NEXT_PUBLIC_SENDGRID_API_KEY}"
  - name: gcr.io/solarcar-website-371620/firebase
    args: ["deploy", "--project=solarcar-website-371620", "--only=hosting"]
