/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 CarModel.glb
Author: SheldonJ99 (https://sketchfab.com/sheldonj99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-rx7-stylised-898e9be8c8964f6298188a2901216e80
Title: Mazda RX7 Stylised
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes } = useGLTF("/CarModel.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -38.5, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 97.28, 0]} rotation={[Math.PI, 0, -3.13]}>
            <group position={[174.74, -50.16, 100.69]}>
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#6_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#6_0"].material}
                material-color="black"
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#8_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#8_0"].material}
                material-color="black"
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#7_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#7_0"].material}
                material-color="black"
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#9_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#9_0"].material}
                material-color="white"
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_02_-_Default_0"].geometry}
                material={nodes["Low_Poly_Rx7_02_-_Default_0"].material}
                material-color="white"
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#17_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#17_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#1_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#1_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#3_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#3_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#4_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#4_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#5_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#5_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#2_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#2_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#14_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#14_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#0_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#0_0"].material}
              />
              <mesh
                geometry={nodes["Low_Poly_Rx7_Material_#19_0"].geometry}
                material={nodes["Low_Poly_Rx7_Material_#19_0"].material}
              />
            </group>
          </group>
        </group>
      </group>
      <pointLight intensity={1} decay={2} position={[33.3, 109.4, 0]} />
    </group>
  );
}

useGLTF.preload("/CarModel.glb");
